services:
  dev:
    build:
      context: .
    image: simple-nginx:dev
    container_name: simple-nginx-dev
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  prod:
    build:
      context: .
    image: simple-nginx:prod
    container_name: simple-nginx-prod
    ports:
      - "8082:80"
    restart: unless-stopped
