name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      DEV_CONTAINER: simple-nginx-dev
      PROD_CONTAINER: simple-nginx-prod
      PROD_PORT: 8082

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Dev Image
      run: |
        docker build -t simple-nginx:dev .

    - name: Start Dev Container
      run: |
        docker run -d --name $DEV_CONTAINER -p 8081:80 simple-nginx:dev

    - name: Wait for Dev Container to be ready
      run: |
        # Loop for up to 30 seconds
        timeout=30
        while [[ $timeout -gt 0 ]]; do
          if curl -fsS http://localhost:8081; then
            echo "Container is ready!"
            exit 0
          fi
          echo "Waiting for container... Retrying in 1 second."
          sleep 1
          timeout=$((timeout-1))
        done
        
        echo "Timeout reached. Container not ready."
        exit 1

    - name: Test Dev Container
      run: |
        curl -fsS http://localhost:8081 | grep -q "God bye from simple-nginx!" || exit 1

    - name: Bump Version
      run: |
        current_version=$(grep -oP 'version: \K[0-9.]+' index.html)
        IFS='.' read -r major minor <<< "$current_version"
        minor=$((minor + 1))
        new_version="$major.$minor"
        sed -i "s/version: $current_version/version: $new_version/" index.html
        echo "New version: $new_version"

    - name: Build Prod Image
      run: |
        docker build -t simple-nginx:prod .

    - name: Start Prod Container
      run: |
        docker run -d --name $PROD_CONTAINER -p $PROD_PORT:80 simple-nginx:prod

    - name: Wait for Prod Container to be ready
      run: |
        timeout=30
        while [[ $timeout -gt 0 ]]; do
          if curl -fsS http://localhost:$PROD_PORT; then
            echo "Prod container is ready!"
            exit 0
          fi
          echo "Waiting for Prod container... Retrying in 1 second."
          sleep 1
          timeout=$((timeout-1))
        done
        echo "Timeout reached. Prod container not ready."
        exit 1

    - name: Test Prod Container
      run: |
        curl -fsS http://localhost:$PROD_PORT | grep -q "Good bye from simple-nginx!" || exit 1

    - name: Stop Containers
      run: |
        docker rm -f $DEV_CONTAINER $PROD_CONTAINER